"""mboek-client: high-level Python client for the mBoek bookkeeping API."""

from mboek._client import MboekClient
from mboek._exceptions import (
    AuthError,
    ConflictError,
    ForbiddenError,
    MboekError,
    NotFoundError,
    RateLimitError,
    ScopeError,
    ValidationError,
)
from mboek.models import (
    Administratie,
    AuthToken,
    AutoBookingRule,
    AutoBookingRuleLine,
    BalansRegel,
    BalansReport,
    Boeking,
    Boekingsregel,
    Boekjaar,
    BoekjaarStatus,
    BtwAangifte,
    BtwBerekening,
    BtwCode,
    BtwSoort,
    Dagboek,
    DagboekType,
    DagboekWerkStatus,
    GrootboekMutatie,
    Grootboekrekening,
    ImportFormaat,
    ImportResult,
    MatchSuggestion,
    NewAutoBookingRuleLine,
    NewBoekingsregel,
    Regeltype,
    RekeningCategorie,
    RekeningType,
    RubriekBedragen,
    WinstVerliesRegel,
    WinstVerliesReport,
)

__all__ = [
    "MboekClient",
    # exceptions
    "MboekError",
    "AuthError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "RateLimitError",
    "ScopeError",
    # models — new canonical names
    "Administratie",
    "AuthToken",
    "AutoBookingRule",
    "AutoBookingRuleLine",
    "Boeking",
    "Boekingsregel",
    "Boekjaar",
    "BtwCode",
    "Dagboek",
    "Grootboekrekening",
    # models — enums / non-response types
    "BoekjaarStatus",
    "BalansRegel",
    "BalansReport",
    "BtwAangifte",
    "BtwBerekening",
    "BtwSoort",
    "DagboekType",
    "DagboekWerkStatus",
    "GrootboekMutatie",
    "ImportFormaat",
    "ImportResult",
    "MatchSuggestion",
    "NewAutoBookingRuleLine",
    "NewBoekingsregel",
    "RekeningCategorie",
    "RekeningType",
    "Regeltype",
    "RubriekBedragen",
    "WinstVerliesRegel",
    "WinstVerliesReport",
]
