"""mboek-client: high-level Python client for the mBoek bookkeeping API."""

from mboek._client import MboekClient
from mboek._exceptions import (
    AuthError,
    ConflictError,
    ForbiddenError,
    MboekError,
    NotFoundError,
    RateLimitError,
    ScopeError,
    ValidationError,
)
from mboek.models import (
    AdministratieResponse,
    AutoBookingRuleLineResponse,
    AutoBookingRuleResponse,
    BalansRegel,
    BalansReport,
    BoekingResponse,
    BoekingsregelResponse,
    Boekjaar,
    BoekjaarStatus,
    BtwAangifte,
    BtwBerekening,
    BtwCodeResponse,
    BtwSoort,
    Dagboek,
    DagboekResponse,
    DagboekType,
    DagboekWerkStatus,
    GrootboekMutatie,
    Grootboekrekening,
    GrootboekrekeningMetSaldoResponse,
    GrootboekrekeningResponse,
    ImportFormaat,
    ImportResult,
    LoginResponse,
    MatchSuggestion,
    NewAutoBookingRuleLine,
    NewBoekingsregel,
    Regeltype,
    RekeningCategorie,
    RekeningType,
    RubriekBedragen,
    WinstVerliesRegel,
    WinstVerliesReport,
)

__all__ = [
    "MboekClient",
    # exceptions
    "MboekError",
    "AuthError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "RateLimitError",
    "ScopeError",
    # models
    "AdministratieResponse",
    "AutoBookingRuleLineResponse",
    "AutoBookingRuleResponse",
    "BalansRegel",
    "BalansReport",
    "BoekingResponse",
    "Boekjaar",
    "BoekjaarStatus",
    "BoekingsregelResponse",
    "BtwAangifte",
    "BtwBerekening",
    "BtwCodeResponse",
    "BtwSoort",
    "Dagboek",
    "DagboekResponse",
    "DagboekType",
    "DagboekWerkStatus",
    "Grootboekrekening",
    "GrootboekMutatie",
    "GrootboekrekeningMetSaldoResponse",
    "GrootboekrekeningResponse",
    "ImportFormaat",
    "ImportResult",
    "LoginResponse",
    "MatchSuggestion",
    "NewAutoBookingRuleLine",
    "NewBoekingsregel",
    "RekeningCategorie",
    "RekeningType",
    "Regeltype",
    "RubriekBedragen",
    "WinstVerliesRegel",
    "WinstVerliesReport",
]
